### ISSUE TITLE
More Branchless Stuff

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/lokacore#22]
Some of these can be `const fn`, most of these are macros.

Good candidates seem to be

* [x] [DetectOppositeSigns](https://graphics.stanford.edu/~seander/bithacks.html#DetectOppositeSigns)
* [x] [DetermineIfPowerOf2](https://graphics.stanford.edu/~seander/bithacks.html#DetermineIfPowerOf2)
* [x] [ConditionalSetOrClearBitsWithoutBranching](https://graphics.stanford.edu/~seander/bithacks.html#ConditionalSetOrClearBitsWithoutBranching)
* [x] [ConditionalNegate](https://graphics.stanford.edu/~seander/bithacks.html#ConditionalNegate)
* [x] [MaskedMerge](https://graphics.stanford.edu/~seander/bithacks.html#MaskedMerge)
* [ ] [SwappingValuesSubAdd](https://graphics.stanford.edu/~seander/bithacks.html#SwappingValuesSubAdd)
* [x] [ReverseByteWith64BitsDiv](https://graphics.stanford.edu/~seander/bithacks.html#ReverseByteWith64BitsDiv)

**Comment by 64** [comment]
There is already a branchless [`is_power_of_two`](https://doc.rust-lang.org/nightly/src/core/num/mod.rs.html#3751-3753) in the standard library

**Comment by Lokathor** [comment]
neat, but not branchless :P

**Comment by 64** [comment]
Isn’t it the exact same as what you linked?

**Comment by Lokathor** [comment]
```rust
            pub fn is_power_of_two(self) -> bool {
                (self.wrapping_sub(1)) & self == 0 && !(self == 0)
            }
```

Note the `&&`, that's short circuit, so not branchless/`const` (under Rust's limited definition of const)

**Comment by Lokathor** [comment]
Oh neat, https://doc.rust-lang.org/nightly/std/primitive.u8.html#method.reverse_bits (1.37 though)

**Comment by 64** [comment]
Ah I see. Confused me because it still generates branchless code on x86. Sorry

**Comment by Lokathor** [comment]
Yeah, there's a few things like that where LLVM is smarter than Rust lets us be right now

**Comment by Lokathor** [comment]
whoops, not in the commit message but here is force bits: https://github.com/Lokathor/lokacore/commit/dfab413825fda3b83147f63b3201811c86e3b940

**Comment by Lokathor** [comment]
mutable references in const fn are unstable, so we'll skip the final add/sub swapper for now
